INSERT INTO clients (CPF, NAME, PHONE) VALUES ('911.037.110-91','Ana Silva', '11 9453345435');
INSERT INTO clients (CPF, NAME, PHONE) VALUES ('502.159.000-65', 'Fernando Nunes', '11 923830384');
INSERT INTO clients (CPF, NAME, PHONE) VALUES ('334.143.460-79', 'Victor Gomes', '11 903059371');

INSERT INTO users (NAME, EMAIL, PASSWORD, ACTIVE) VALUES ('André Franco', 'andrefranco@email.com', '123456', TRUE);

INSERT INTO roles (ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO roles (ROLE) VALUES ('ROLE_OPERATOR');

INSERT INTO user_roles (ROLE_ID, USER_ID) VALUES (1, 1);
INSERT INTO user_roles (ROLE_ID, USER_ID) VALUES (2, 1);

INSERT INTO products (CODE, NAME, COST_PRICE, SALE_PRICE, PRODUCT_TYPE) VALUES ('ARM001', 'Armação receituário Keen', 50, 150, 'FRAME');
INSERT INTO products (CODE, NAME, COST_PRICE, SALE_PRICE, PRODUCT_TYPE) VALUES ('LEN001', 'Lente Kodak', 200, 420, 'LENS');

INSERT INTO frames (STOCK_QUANTITY, FRAME_CATEGORY, PRODUCT_ID) VALUES (150, 'PRESCRIPTION', 1);

INSERT INTO lenses (LENS_TYPE, PRODUCT_ID) VALUES ('MONOFOCAL', 2);

INSERT INTO sales (ISSUE_DATE, DELIVERY_DATE, ESTIMATED_DELIVERY_DATE, TOTAL_AMOUNT, PAYMENT_METHOD, INSTALLMENTS, COMMENTS, SALE_STATUS, CLIENT_ID, USER_ID, CARD_BRAND) 
VALUES ('2025-06-26', '2025-06-26', '2025-06-26', 389.90, 'CASH', NULL, 'this is a comment of the sale', 'PENDING', 2, 1, NULL);

INSERT INTO sale_items (PRODUCT_ID, SALE_ID, PRICE) VALUES (1, 1 , 150);
INSERT INTO sale_items (PRODUCT_ID, SALE_ID, PRICE) VALUES (2, 1, 420);